"""Paper-shaped toy examples for speculative decoding.

This file teaches the original Leviathan, Kalman, and Matias mechanism
without loading a Transformer model. It focuses on the exact sampling
argument:

- a draft distribution q proposes a token;
- the target distribution p accepts it with probability min(1, p/q);
- if the token is rejected, we sample from norm(max(0, p - q));
- the resulting token distribution is exactly p.

Run:
    .\\.venv\\Scripts\\python.exe learning\\speculative-decoding\\src\\speculative_original_minimal.py
"""
from __future__ import annotations

from dataclasses import dataclass


def normalize(xs: list[float]) -> list[float]:
    total = sum(xs)
    if total <= 0:
        raise ValueError("cannot normalize a non-positive vector")
    return [x / total for x in xs]


def check_distribution(p: list[float], q: list[float]) -> None:
    if len(p) != len(q):
        raise ValueError("p and q must have the same support")
    if any(x < 0 for x in p + q):
        raise ValueError("probabilities must be non-negative")
    if abs(sum(p) - 1.0) > 1e-9 or abs(sum(q) - 1.0) > 1e-9:
        raise ValueError("p and q must both sum to 1")


def overlap_mass(p: list[float], q: list[float]) -> float:
    """Return sum_x min(p(x), q(x)), the expected acceptance rate."""
    check_distribution(p, q)
    return sum(min(pi, qi) for pi, qi in zip(p, q))


def residual_distribution(p: list[float], q: list[float]) -> list[float]:
    """Distribution used after rejecting a draft token."""
    check_distribution(p, q)
    residual = [max(0.0, pi - qi) for pi, qi in zip(p, q)]
    if sum(residual) <= 1e-12:
        return list(p)
    return normalize(residual)


def exact_one_step_output_distribution(p: list[float], q: list[float]) -> list[float]:
    """Enumerate the speculative-sampling output distribution exactly."""
    check_distribution(p, q)
    accept_part = [min(pi, qi) for pi, qi in zip(p, q)]
    reject_mass = 1.0 - sum(accept_part)
    residual = residual_distribution(p, q)
    return [a + reject_mass * r for a, r in zip(accept_part, residual)]


def expected_tokens_per_iteration(alpha: float, gamma: int) -> float:
    """Expected tokens generated by Algorithm 1 under iid acceptance."""
    if gamma < 1:
        raise ValueError("gamma must be positive")
    if alpha < 0 or alpha > 1:
        raise ValueError("alpha must be in [0, 1]")
    if abs(alpha - 1.0) < 1e-12:
        return float(gamma + 1)
    return (1.0 - alpha ** (gamma + 1)) / (1.0 - alpha)


def walltime_speedup(alpha: float, gamma: int, draft_cost_ratio: float) -> float:
    """Theorem-style speedup with one target run and gamma draft runs."""
    expected = expected_tokens_per_iteration(alpha, gamma)
    return expected / (1.0 + gamma * draft_cost_ratio)


def best_gamma(alpha: float, draft_cost_ratio: float, max_gamma: int = 32) -> tuple[int, float]:
    """Choose gamma that maximizes the simple theoretical speedup."""
    candidates = [
        (gamma, walltime_speedup(alpha, gamma, draft_cost_ratio))
        for gamma in range(1, max_gamma + 1)
    ]
    return max(candidates, key=lambda item: item[1])


@dataclass(frozen=True)
class PaperCase:
    name: str
    alpha: float
    gamma: int
    draft_cost_ratio: float

    @property
    def expected_tokens(self) -> float:
        return expected_tokens_per_iteration(self.alpha, self.gamma)

    @property
    def speedup(self) -> float:
        return walltime_speedup(self.alpha, self.gamma, self.draft_cost_ratio)


def summarize() -> dict[str, object]:
    p = [0.50, 0.30, 0.20]
    q = [0.35, 0.45, 0.20]
    out = exact_one_step_output_distribution(p, q)

    t5_small_ende_temp0 = PaperCase(
        name="T5-small draft for T5-XXL EnDe temp0",
        alpha=0.75,
        gamma=7,
        draft_cost_ratio=0.02,
    )
    best = best_gamma(alpha=0.75, draft_cost_ratio=0.02, max_gamma=16)

    return {
        "target_distribution": p,
        "draft_distribution": q,
        "exact_output_distribution": out,
        "overlap_alpha": overlap_mass(p, q),
        "t5_small_expected_tokens": t5_small_ende_temp0.expected_tokens,
        "t5_small_speedup_model": t5_small_ende_temp0.speedup,
        "best_gamma_for_alpha_0_75_c_0_02": best,
    }


def _self_test() -> None:
    result = summarize()
    target = result["target_distribution"]
    output = result["exact_output_distribution"]
    assert all(abs(a - b) < 1e-9 for a, b in zip(target, output))
    assert abs(result["overlap_alpha"] - 0.85) < 1e-9
    assert result["t5_small_expected_tokens"] > 3.0
    assert result["t5_small_speedup_model"] > 2.0

    for key, value in result.items():
        print(f"{key}: {value}")
    print("speculative_original_minimal self-test passed")


if __name__ == "__main__":
    _self_test()
