"""Magpie 风格 instruction 合成 — 教学版.

教学目标：
    1. 用 instruct 模型"自问自答"
    2. 无 seed 全合成
    3. mock 模式：用模板而非真模型（避免 GPU 依赖）

运行：
    python magpie_synthesis.py --demo
    python magpie_synthesis.py --real --model Qwen/Qwen2.5-0.5B-Instruct
"""
from __future__ import annotations

import argparse
import random
from typing import Iterable


# --- Mock 模板：用预设模式模拟 Magpie 输出 ---
INSTRUCTION_TEMPLATES = [
    "Explain {topic} in simple terms.",
    "Write a Python function to {action}.",
    "What are the key differences between {a} and {b}?",
    "Summarize the main idea of {book} in three sentences.",
    "Solve: if {x} + {y} = {z}, what is {x}?",
    "Translate the following sentence to French: \"{sentence}\"",
    "Give me five tips for {task}.",
    "Describe a typical day in the life of {role}.",
]
TOPICS = ["photosynthesis", "quantum entanglement", "blockchain", "mitochondria",
          "general relativity", "neural networks"]
ACTIONS = ["sort a list", "compute factorial", "reverse a string",
           "check if a number is prime", "implement quicksort"]
PAIRS = [("REST", "GraphQL"), ("Python", "Rust"), ("MySQL", "PostgreSQL"),
         ("TCP", "UDP")]
BOOKS = ["1984", "Brave New World", "Dune", "Foundation"]
SENTENCES = ["The cat sits on the mat.", "Knowledge is power.",
             "Time waits for no one."]
TASKS = ["learning a new language", "writing a research paper",
         "preparing for a marathon"]
ROLES = ["a software engineer", "a marine biologist", "a chef"]


def _mock_instruction(rng: random.Random) -> str:
    t = rng.choice(INSTRUCTION_TEMPLATES)
    return t.format(
        topic=rng.choice(TOPICS),
        action=rng.choice(ACTIONS),
        a=rng.choice(PAIRS)[0], b=rng.choice(PAIRS)[1],
        book=rng.choice(BOOKS),
        x=rng.randint(2, 20), y=rng.randint(2, 20), z=rng.randint(20, 60),
        sentence=rng.choice(SENTENCES),
        task=rng.choice(TASKS),
        role=rng.choice(ROLES),
    )


def _mock_response(instruction: str) -> str:
    return (f"Here is a response to: \"{instruction[:50]}...\". "
            "This is a mock answer generated by a deterministic template. "
            "In a real Magpie pipeline, the model itself would write this.")


def magpie_mock(n: int = 10, seed: int = 42) -> Iterable[dict]:
    rng = random.Random(seed)
    for _ in range(n):
        inst = _mock_instruction(rng)
        resp = _mock_response(inst)
        yield {"instruction": inst, "response": resp, "mode": "mock"}


def magpie_real(n: int, model_name: str) -> Iterable[dict]:
    """真实 Magpie：用 instruct 模型自问自答."""
    from transformers import AutoTokenizer, AutoModelForCausalLM
    import torch
    tok = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(
        model_name, torch_dtype=torch.bfloat16, device_map="auto"
    )
    chat_inst = tok.apply_chat_template(
        [{"role": "user", "content": ""}],
        tokenize=False, add_generation_prompt=False,
    )
    # Magpie 的 trick: 截断到 user 起始处让模型自由 continue
    eot = "<|im_end|>"
    inst_prefix = chat_inst.split(eot)[0] + ""    # 保留 user 起始 token

    for _ in range(n):
        inp = tok(inst_prefix, return_tensors="pt").to(model.device)
        out = model.generate(**inp, max_new_tokens=120, do_sample=True,
                             top_p=0.95, temperature=1.0)
        full = tok.decode(out[0], skip_special_tokens=False)
        # 抽出 user 部分
        try:
            inst = full.split(inst_prefix)[1].split(eot)[0].strip()
        except IndexError:
            continue
        if not inst:
            continue

        chat_resp = tok.apply_chat_template(
            [{"role": "user", "content": inst}],
            tokenize=False, add_generation_prompt=True,
        )
        inp2 = tok(chat_resp, return_tensors="pt").to(model.device)
        out2 = model.generate(**inp2, max_new_tokens=200, do_sample=True,
                              top_p=0.95, temperature=0.7)
        resp = tok.decode(out2[0][inp2.input_ids.shape[1]:],
                          skip_special_tokens=True).strip()
        yield {"instruction": inst, "response": resp, "mode": "real"}


def run_demo(n: int = 5) -> None:
    print(f"--- Magpie mock 模式（不调真模型）---\n")
    for i, item in enumerate(magpie_mock(n=n, seed=42), 1):
        print(f"[{i}] inst: {item['instruction']}")
        print(f"    resp: {item['response'][:80]}...")
        print()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--demo", action="store_true")
    ap.add_argument("--real", action="store_true")
    ap.add_argument("--model", type=str, default="Qwen/Qwen2.5-0.5B-Instruct")
    ap.add_argument("-n", type=int, default=5)
    args = ap.parse_args()

    if args.real:
        for item in magpie_real(args.n, args.model):
            print(item)
    elif args.demo:
        run_demo(args.n)


if __name__ == "__main__":
    main()
